# Sant-Resume
Bracken Sant   
https://github.com/bracken576/Sant-Resume.git   
903-439-5495 | bsant576@byui.edu   
[Linked-In Profile](https://linkedin.com/in/bracken-sant-70b76a192)
# Summary
I have been programming for 4 years in Python and 1 year in R. I have also used other programming languages, but these are the ones that I am the most comfortable with and the most applicable to data science. I have studied statistics and am familiar with multiple libraries in Python and R used for data manipulation and visualization. 
# Skills
•	Data Manipulation &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; • R (Advanced)

•	Data Visualization &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; • Machine Learning

•	Python (Advanced) &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; • Git	

•	MySQL   

# Education:
**Data Science Major, Brigham Young University Idaho, April 2022 - Dec 2025**

# Experience
## Math & Data Science TA, Brigham Young University Idaho, January 2024 - Present, Rexburg, ID

•	Worked with instructor to create curriculum within a Statistics class in R.

•	Helped students work through errors in code and helped them become independent.

•	Helped students download software and fix issues with installations.

## Data Science Tutor, Brigham Young University Idaho, January 2024 - Present, Rexburg, ID
• Helped students understand the fundamentals of R and Python programming in the Data Science field.  

• Worked with others to establish an open place for learning and teaching.

• Demonstrated coding techniques and how to utilize functions within R and Python.

## Programming Intern, Fidelity Express, September 2019-March 2020, Sulphur Springs, TX
•	Compiled data and worked on programming to sort through data.

• Communicated with co-workers to work more effectively.


